- dcspy/dcsbios.py
- dcspy/parser_states.puml
- setup.cfg
- tests/test_dcsbios.py
Rework `process_byte()` in `ProtocolParser` to be more readable and simpler.
> new state machine in parser

- dcspy/aircrafts.py
- tests/test_aircraft.py
> Full support for Ka-50 PVI-800

- dcspy/dcspy.py
Format waiting time before connection to DCS
> format waiting time

- dcspy/__init__.py
- dcspy/dcsbios.py
- dcspy/dcspy.py
- dcspy/logitech.py
- tests/test_dcsbios.py
Switch from TCP to UDP as suggestet here: [Connecting to DCS-BIOS via UDP](https://github.com/DCSFlightpanels/dcs-bios/blob/master/Scripts/DCS-BIOS/doc/developerguide.adoc#connecting-to-dcs-bios)
Multicast in Python: 
* https://wiki.python.org/moin/UdpCommunication
* https://pymotw.com/2/socket/multicast.html
> support for UDP

- .travis.yml
> Configure CI for windows

- README.md
- dcspy/aircrafts.py
Looks like F-16C DED support not working
> Fix F-16 DED

- tests/test_dcsbios.py
Cover `StringBuffer()` with unit tests
> testting string buffer

- dcspy/__init__.py
- dcspy/aircrafts.py
- tests/conftest.py
- tests/test_aircraft.py
> Basic support for F-14

- CONTRIBUTING.md
- dcspy/aircrafts.py
- setup.cfg
- tests/conftest.py
- tests/test_aircraft.py
- tests/test_bios.py
- tests/utils.py
Track  DCS-BIOS to detect JSON changes, which can affect DCSpy
> Test and track DCS-BIOS changes

- dcspy/starter.py
- dcspy/tk_gui.py
- dcspy/utils.py
- requirements.txt
- setup.cfg
- tests/test_starter.py
- tests/test_utils.py
Check local and remote version of DCS-BIOS and allow to remove old and overwrite new in `Saved Games` folder
There are many places when things can go wrong - try handle those.
> Check, download and update DCS-BIOS

- dcspy/__init__.py
- dcspy/aircrafts.py
- dcspy/logitech.py
- dcspy/utils.py
- tests/conftest.py
- tests/test_aircraft.py
- tests/test_logitech.py
- tests/test_utils.py
- uml/classes.puml
Add extra foreground and background color parameter to `LcdSize` named tuple, which will simplify drawing at LCD.
* #23
> Add fg and bg to LcdSize tuple

- dcspy/__init__.py
- dcspy/dcspy.py
- dcspy/utils.py
- resources/config.yaml
- tests/test_utils.py
Allow starting with or without GUI
~~- [ ] by CLI parameter~~
* #27
> Start GUI can be optional

- .github/workflows/python-ci.yml
- dcspy/__init__.py
- dcspy/aircrafts.py
- tests/test_aircraft.py
Improve CI and try install MS Clear Fonts at Ubuntu during CI
> nstall ms fonts during ci at ubuntu

- .github/workflows/python-ci.yml
- README.md
- dcspy/__init__.py
- dcspy/aircrafts.py
- dcspy/logitech.py
- dcspy/utils.py
- resources/config.yaml
- tests/test_logitech.py
- tests/test_utils.py
Add font name and size to config.yaml and use in dynamic way during usage of DCSpy
How handle font name issue ? - Add font during CI, linux is used only for CI.
> Use fonts in dynamic way

- README.md
- dcspy/tk_gui.py
- dcspy/utils.py
- tests/test_utils.py
Make first installation of DCS-BIOS painless for new users
> Install DCS-BIOS for new users

- dcspy/config.yaml
- dcspy/tk_gui.py
- dcspy/utils.py
- tests/test_utils.py
Allow DCSpy autostart during lunch
Set dafalut to False
`autostart: false`
> Autostart DCSpy when lunching

- dcspy/aircraft.py
- dcspy/log.py
- dcspy/tk_gui.py
use python way to select temporary directory instead of using TEMP environment variable.
> Use temp directory in proper way

- dcspy/__init__.py
- dcspy/aircraft.py
- dcspy/logitech.py
- tests/test_aircraft.py
- tests/test_logitech.py
- uml/classes.puml
use enum for LCD type instead of pure int
> Enum LCD type

- CHANGELOG.md
- dcspy/aircraft.py
- tests/test_aircraft.py
Improve handling button of F-18 Hornet for G19
> Add button for Hornet G19

- CHANGELOG.md
- CONTRIBUTING.md
- dcspy/__init__.py
- dcspy/logitech.py
- uml/classes.puml
Optimize `LcdInfo` dataclass - add buttons enum
> Move buttons enum to dataclass

- dcspy/dcsbios.py
- tests/test_dcsbios.py
- uml/classes.puml
Support enum for state in `dcsbios` module
> Add enum fo DCS-BIOS module

- .github/workflows/python-ci.yml
- .github/workflows/tox.yml
- README.md
- requirements.txt
- requirements_test.txt
- setup.cfg
Add support for Python 3.11
Force using newest Pillow 9.3.0
> Support Python 3.11

- dcspy/tk_gui.py
Toggle state of Start/Stop buttons
> Toggle state of Start/Stop buttons

- CHANGELOG.md
- dcspy/tk_gui.py
Update `packaging` package to 22.0 version
> Update packaging package

- dcspy/tk_gui.py
- dcspy/utils.py
- tests/test_utils.py
Add simple information as last tab
> Add About tab

- CHANGELOG.md
- requirements.txt
A few sentences describing the overall goals of the pull request's commits.
* #116
> Fix no dcspy icon for customtkinter

- CHANGELOG.md
- CONTRIBUTING.md
- dcspy/__init__.py
- dcspy/aircraft.py
- dcspy/logitech.py
- dcspy/tk_gui.py
- requirements.txt
- setup.cfg
- tests/helpers.py
- tests/test_aircraft.py
- uml/classes.puml
> Typing checking improvments

- CHANGELOG.md
- dcspy/log.py
`verbose` setting should impact both file and stream log handler
* #129
> Verbose flag

- dcspy/tk_gui.py
- requirements.txt
- setup.cfg
Use package: https://github.com/Akascape/CTkMessagebox
* #132
> Custom msgboxes

- dcspy/tk_gui.py
* save
* undo selection
There is no way to set back previous color is user clicked no at msgbox
* #134
> Cancel color change not working

- .github/workflows/qodana.yml
- CHANGELOG.md
- dcspy/tk_gui.py
Let user know there is problem with DCS-BIOS folder location.
Check DCS-BIOS path:
* is not empty
* drive letter exists in system
> No DCS-BIOS folder

- dcspy/starter.py
Add Alexander Leschanz as supporter.
> update supporters banner

- CHANGELOG.md
- README.md
- dcspy/tk_gui.py
- dcspy/utils.py
Check if git executable is available in system and if not disable usage of BIOS live feature.
> Prevent failure when git is not available

- CHANGELOG.md
- CONTRIBUTING.md
- dcspy/aircraft.py
- tests/test_aircraft.py
- uml/classes.puml
Be clever with handling buttons regular and cycle. Do more work in base `Aircraft` object, less in children.
> Change button handling

- .github/workflows/test.yml
- CHANGELOG.md
- dcspy/tk_gui.py
- dcspy/utils.py
- pyproject.toml
- requirements.txt
- requirements_test.txt
- tests/test_aircraft.py
- tests/test_utils.py
Use new packaging version
* #162
> Use new packaging version

- dcspy/tk_gui.py
- dcspy/utils.py
Add button for collecting data for troubleshooting (at About tab)
* #139
> Add button for collecting data

- .github/workflows/test.yml
- pyproject.toml
- requirements_test.txt
replace old pytest-random with newer randomly
> Add pytest-randomly

- dcspy/aircraft.py
- tests/conftest.py
- tests/test_aircraft.py
Update DCS-BIOS values for controls.
> Align BIOS

- CHANGELOG.md
- dcspy/__init__.py
- dcspy/aircraft.py
- dcspy/logitech.py
- dcspy/models.py
- dcspy/qt_gui.py
- dcspy/sdk/lcd_sdk.py
- dcspy/sdk/led_sdk.py
- dcspy/starter.py
- dcspy/tk_gui.py
- tests/conftest.py
- tests/test_aircraft.py
- tests/test_bios.py
- tests/test_logitech.py
- tests/test_starter.py
* Logitech Manager
* Clean-up models
* Use Keyboard model in GUI
* Claen-up loading order
> Update start process

- CHANGELOG.md
- dcspy/__init__.py
- dcspy/aircraft.py
- dcspy/logitech.py
- dcspy/run.py
- dcspy/starter.py
- tests/conftest.py
- tests/helpers.py
- tests/test_aircraft.py
- tests/test_dcspy.py
- tests/test_logitech.py
- uml/classes.puml
Basic and advanced plane/mode support
> Basic and advanced plane/mode support

- .pre-commit-config.yaml
- README.md
- pyproject.toml
- requirements.txt
- requirements_test.txt
- sonar-project.properties
Try update to PySide6 ver. 6.6.0
> PySide6 6.6.0

- .github/actions/build-app/action.yaml
- .pre-commit-config.yaml
- dcspy.spec
- dcspy/__init__.py
- dcspy/models.py
- dcspy/qt_gui.py
- dcspy/run.py
- dcspy/starter.py
- dcspy/utils.py
- dcspy_cli.spec
- dcspy_onedir.spec
- generate_ver_file.py
- pyproject.toml
- requirements_test.txt
Check [Nuitka](https://doc.qt.io/qtforpython-6/deployment/deployment-nuitka.html)/[PyInstaller](https://doc.qt.io/qtforpython-6/deployment/deployment-pyinstaller.html) resources
> PyInstaller, Nuitka and whl

- dcspy/__init__.py
- dcspy/config.yaml
- dcspy/migration.py
- dcspy/models.py
- dcspy/qt_gui.py
- dcspy/utils.py
- tests/conftest.py
- tests/resources/c.yml
- tests/test_migration.py
- tests/test_utils.py
> Migration of cimfiguration

- .pre-commit-config.yaml
- CONTRIBUTING.md
- dcspy/__init__.py
- dcspy/aircraft.py
- dcspy/logitech.py
- dcspy/migration.py
- dcspy/models.py
- dcspy/qt_gui.py
- dcspy/sdk/key_sdk.py
- dcspy/starter.py
- dcspy/ui/qtdcs.ui
- dcspy/utils.py
- pyproject.toml
- requirements_test.txt
- tests/conftest.py
- tests/test_aircraft.py
- tests/test_led_sdk.py
- tests/test_logitech.py
- tests/test_models.py
- tests/test_qtgui.py
- tests/test_utils.py
- uml/classes.puml
Clean-up unit test `models` and `utils`
> Clean-up test, models and utils

- CHANGELOG.md
- dcspy/qt_gui.py
- dcspy/utils.py
- tests/test_utils.py
Report progress of live DCS-BIOS installation gradually
> Git pull progress

- CHANGELOG.md
- pyproject.toml
- requirements.txt
Update PySide6 version in project dependencies
> PySide6 6.6.1

- CHANGELOG.md
- dcs_py.py
Add error handling for missing Git installation
* #232
> Add error handling for missing Git installation

- CHANGELOG.md
- dcspy/__init__.py
- dcspy/migration.py
Start logging from very beginning
* #243
> Start logging from very beginning

- CHANGELOG.md
- dcspy/models.py
- tests/test_models.py
Some custom request from config file are set as a different type
* #256
> Wrong type for request

- .pre-commit-config.yaml
- dcspy/models.py
- dcspy/qt_gui.py
- dcspy/qtgui.qrc
- dcspy/ui/qtdcs.ui
- tests/test_models.py
- tests/test_qtgui.py
Add new set state action for controllers.
> Add new set state action

- .pre-commit-config.yaml
- CHANGELOG.md
- dcspy/dcsbios.py
- dcspy/logitech.py
- dcspy/starter.py
- requirements_test.txt
- tests/test_logitech.py
Unload previous plane when loading next one - remove old BIOS callbacks
> Unload previous airplane

- dcs_py.py
- dcspy/aircraft.py
- dcspy/logitech.py
- dcspy/qt_gui.py
- dcspy/run.py
- dcspy/sdk/key_sdk.py
- dcspy/sdk/lcd_sdk.py
- dcspy/starter.py
- tests/conftest.py
- tests/helpers.py
- tests/test_aircraft.py
- tests/test_key_sdk.py
- tests/test_lcd_sdk.py
- tests/test_logitech.py
- uml/classes.puml
Part of bigger feature, despite lack of LCD make DCSpy run  fine.
> Make LCD optional

- .github/workflows/release-ci.yml
- .pre-commit-config.yaml
- CHANGELOG.md
- dcspy.spec
- dcspy/qt_gui.py
- dcspy_cli.spec
- dcspy_onedir.spec
- requirements_test.txt
* Make sure build always exec without version to update local version easier
* auto restart DCSpy when new version is downloaded
> Rename exec during CI process

- .github/workflows/test.yml
- .pre-commit-config.yaml
- README.md
- pyproject.toml
- sonar-project.properties
> Remove support for Python 3.8

- .pre-commit-config.yaml
- dcspy/aircraft.py
- dcspy/dcsbios.py
- dcspy/logitech.py
- dcspy/migration.py
- dcspy/models.py
- dcspy/qt_gui.py
- dcspy/sdk/lcd_sdk.py
- dcspy/sdk/led_sdk.py
- dcspy/starter.py
- dcspy/ui/qtdcs.ui
- dcspy/utils.py
- generate_ver_file.py
- pyproject.toml
- requirements.txt
- requirements_test.txt
- tests/helpers.py
Update PySide6/Qt to 6.7.0 as well as Pydantic
> Update PySide6/Qt to 6.7.0

- dcspy/qt_gui.py
Fix starting DCSpy with new devices
> Fix starting DCSpy with new devices

- dcspy/sdk/key_sdk.py
- tests/test_key_sdk.py
> Add mouse to G-key SDK

- dcspy/qt_gui.py
- dcspy/utils.py
- tests/test_utils.py
Fix update process for PyInstaller version
> Fix update process

- .github/workflows/coverage.yml
- .github/workflows/test.yml
- CHANGELOG.md
- dcspy/qt_gui.py
- dcspy/utils.py
Generate BIOS JSON's during start of GUI
> Generate BIOS JSON's during start of GUI

- .pre-commit-config.yaml
- CHANGELOG.md
- dcspy/qt_gui.py
- dcspy/run.py
- pyproject.toml
- tox.ini
When BIOS configuration is wrong main window get hide in system tray. This should not happened.
* #354
> Do not hide main window

- CHANGELOG.md
- dcspy/qt_gui.py
- dcspy/utils.py
- tests/test_utils.py
check if BIOS JSON's files exist before do generation and compilation
> Check if JSONs exit before compilation

- CHANGELOG.md
- dcspy/qt_gui.py
Enable generation of BIOS JSON files
> Enable generation of BIOS JSON files

- CHANGELOG.md
- pyproject.toml
- requirements_dev.txt
- requirements_test.txt
- uv.lock
> Introduction of UV tool

- pyproject.toml
- requirements.txt
- src/dcspy/__init__.py
- src/dcspy/aircraft.py
- src/dcspy/dcsbios.py
- src/dcspy/migration.py
- src/dcspy/models.py
- src/dcspy/qt_gui.py
- src/dcspy/sdk/__init__.py
- src/dcspy/sdk/key_sdk.py
- src/dcspy/utils.py
Use Python 3.10 Annotations and fix Pydantic pydantic/pydantic#7873 for Python 3.9
> Use Python 3.10 Annotations

- .github/workflows/codspeed.yml
- README.md
- pyproject.toml
- requirements_test.txt
- tests/test_aircraft.py
- tests/test_logitech.py
- tests/test_models.py
> Add Codspeed to CI process

- CHANGELOG.md
- src/dcspy/qt_gui.py
- src/dcspy/utils.py
Report progress when downloading files
> Report progress when downloading files

- CHANGELOG.md
- src/dcspy/logitech.py
- src/dcspy/sdk/lcd_sdk.py
- src/dcspy/starter.py
- tests/test_logitech.py
- tests/test_starter.py
- uml/classes.puml
> Lcd is not cleared

- pyproject.toml
- src/dcspy/__init__.py
- src/dcspy/logitech.py
- src/dcspy/migration.py
- src/dcspy/models.py
- src/dcspy/qt_gui.py
- src/dcspy/run.py
- src/dcspy/starter.py
- src/dcspy/utils.py
- tests/conftest.py
- tests/test_logitech.py
- tests/test_starter.py
- tests/test_utils.py
- uml/classes.puml
Use LCD text mode in welcome and waiting screen.
> LCD text mode

- CHANGELOG.md
- src/dcspy/migration.py
- src/dcspy/qt_gui.py
- src/dcspy/resources/config.yaml
- src/dcspy/utils.py
- tests/conftest.py
- tests/resources/config.yaml
- tests/test_migration.py
- tests/test_utils.py
DCS-BIOS change default branch form `master` to `main`
❗ **Check** if `is_git_object(repo_dir: Path, git_obj: str)` function from `utils`
need checkout default branch (master/main) to be able verify existence of Git object/reference:
```python
bios_repo.git.checkout('master')
```
* #447
> DCS-BIOS new default branch

- .github/workflows/license.yml
> Fix CI license check

- .github/actions/setup-python/action.yaml
- .github/workflows/coverage.yml
- .github/workflows/license.yml
- .github/workflows/nuitka.yml
- .github/workflows/pyinstaller.yml
- .github/workflows/sonarcloud.yml
- .github/workflows/style.yml
- .github/workflows/test.yml
> Introduce uv

- .github/workflows/license.yml
Chnages due tu fixed issue: pilosus/action-pip-license-checker#62
> New license check

- src/dcspy/qt_gui.py
- src/dcspy/ui/about.ui
> New About dialog
